### ISSUE TITLE
希望纠正博客内容

### ISSUE THREAD

**Issue by HelloCodel** [yabea/python-tutorial#2]
您的博客链接如下：https://www.jb51.net/article/173950.htm
[
![image](https://user-images.githubusercontent.com/49329864/89397088-f9ae0980-d741-11ea-85da-ae5e707bf1b0.png)
](url)
将“utf8”错写成了“uft8”
相信应该是手误，但如果看博客的人直接把这个复制下来修改，运行时会有错误，检查错误时很容易忽视这个，希望博主改一下，谢谢！

**Comment by yabea** [comment]
这个 blog 是转载我的哈，我的 [blog](https://www.cnblogs.com/ybjourney/p/11832045.html ) 是对的哈
